language: objective-c
osx_image: xcode9.4
env: LC_CTYPE=en_US.UTF-8
script: 
  - xcodebuild test -workspace AZDateBuilder.xcworkspace -scheme LogicTests -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X'
